### ISSUE TITLE
Error with ALL-LANGUAGES-CODES file

### ISSUE THREAD

**Issue by joset98** [victor-heliomar/i18n-translation-generator#39]
When you try to run and translate with the command, the console throws this error

>![image](https://github.com/victor-heliomar/i18n-translation-generator/assets/49282275/26bf82dd-f0b2-4435-aa30-4bcf11021cac)

**Comment by victor-heliomar** [comment]
OH, my bad!.

Thanks for notifying! Will solve it ASAP

**Comment by victor-heliomar** [comment]
Just published a new version on npm solving this bug. 

Performed some tests locally and worked fine to me!

![image](https://github.com/victor-heliomar/i18n-translation-generator/assets/66505715/fb876703-31b8-4871-aa82-84b1e49014aa)

Please try again and let me know if it works on your side

Feel free of close the issue if it works on your side

**Comment by joset98** [comment]
> Just published a new version on npm solving this bug.
> 
> Performed some tests locally and worked fine to me!
> 
> ![image](https://user-images.githubusercontent.com/66505715/284981503-fb876703-31b8-4871-aa82-84b1e49014aa.png)
> 
> Please try again and let me know if it works on your side
> 
> Feel free of close the issue if it works on your side

Good it was solved!
>![image](https://github.com/victor-heliomar/i18n-translation-generator/assets/49282275/a874589f-f9af-4548-a54f-b463e49a0db0)

**Comment by victor-heliomar** [comment]
Great! thanks for confirm
